### ISSUE TITLE
Shakespeare demo broken at save points

### ISSUE THREAD

**Issue by jkahn** [google/prettytensor#16]
Running out of the box, the shakespeare tutorial crashes with a broken feed value.  I am running the tensorflow (0.7.1) and pretty tensor (0.5.3) versions that are the latest right now.

mnist.py does not have the same issue, despite the apparent use of the same data_utils frameworks (permute_data, etc).  Help? 
```
$ python /usr/share/anaconda/anaconda2/envs/tf2/lib/python2.7/site-packages/prettytensor/tutorial/shakespeare.py --epochs 2 --save_path /home/jeremy/notebooks/shakespeare/
Starting Shakespeare
W tensorflow/core/common_runtime/executor.cc:1102] 0x15629680 Compute status: Invalid argument: You must feed a value for placeholder tensor 'shakespeare_2/Placeholder' with dtype int32
         [[Node: shakespeare_2/Placeholder = Placeholder[dtype=DT_INT32, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
         [[Node: _send_shakespeare/cross_entropy/truediv_2_0 = _Send[T=DT_FLOAT, client_terminated=true, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=-2958238964605934168, tensor_name="shakespeare/cross_entropy/truediv_2:0", _device="/job:localhost/replica:0/task:0/cpu:0"](shakespeare/cross_entropy/truediv_2)]]
Traceback (most recent call last):
  File "/usr/share/anaconda/anaconda2/envs/tf2/lib/python2.7/site-packages/prettytensor/tutorial/shakespeare.py", line 249, in <module>
    tf.app.run()
  File "/usr/share/anaconda/anaconda2/envs/tf2/lib/python2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/usr/share/anaconda/anaconda2/envs/tf2/lib/python2.7/site-packages/prettytensor/tutorial/shakespeare.py", line 226, in main
    print_every=10)
  File "/usr/share/anaconda/anaconda2/envs/tf2/lib/python2.7/site-packages/prettytensor/local_trainer.py", line 216, in train_model
    print_every=print_every)[2:]
  File "/usr/share/anaconda/anaconda2/envs/tf2/lib/python2.7/site-packages/prettytensor/local_trainer.py", line 166, in run_model
    dict(zip(feed_vars, data)))
  File "/usr/share/anaconda/anaconda2/envs/tf2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 315, in run
    return self._run(None, fetches, feed_dict)
  File "/usr/share/anaconda/anaconda2/envs/tf2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 511, in _run
    feed_dict_string)
  File "/usr/share/anaconda/anaconda2/envs/tf2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 564, in _do_run
    target_list)
  File "/usr/share/anaconda/anaconda2/envs/tf2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 586, in _do_call
    e.code)
```

**Comment by jkahn** [comment]
FWIW this crash seems to be happening in the summary-writer train-steps, not the "vanilla" run iterations.

**Comment by jkahn** [comment]
setting save_path to None avoids this crash but results in no checkpoints. :(

**Comment by eiderman** [comment]
I've dug into it and it appears that the problem is the inference graph by default creates summaries, which depend on the placeholder.

Default summaries are great for diagnosing the problem, but I think fixing this correctly requires a scoped method to disable summaries and/or put them in a different graph collection so that the training sub-graph doesn't pick up a dependency on the inference sub-graph.

**Comment by jkahn** [comment]
I don't really follow this explanation, but if I remove the inference graph and the calls to it, I can indeed make it train with a non-empty save path.  But I see no new files showing up in the specified save path, so I wonder if I've missed something.

Is there another workaround to disable the summaries in the inference graph?

**Comment by jkahn** [comment]
I don't really follow this explanation, but if I remove the inference graph and the calls to it, I can indeed make it train with a non-empty save path.  But I see no new files showing up in the specified save path, so I wonder if I've missed something.

Is there another workaround to disable the summaries in the inference graph?

**Comment by jkahn** [comment]
Should I change something in create_model so that if phase==infer it *doesn't* construct the extra summaries?

**Comment by eiderman** [comment]
There wasn't an option before. With the most recent push you can control where summaries are placed (which graph collection has them). 

I will package it up later this week for pip.

**Comment by eiderman** [comment]
Uploaded package to pip; see CHANGELOG for more details.
