### ISSUE TITLE
AttributeError after updating to Tensorflow 0.7.1 

### ISSUE THREAD

**Issue by vignesh10** [google/prettytensor#19]
Hi,

I recently upgraded to tensorflow version 0.7.1 and immediately I got this error when importing prettytensor. 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/__init__.py", line 22, in <module>
    from prettytensor import funcs
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/funcs.py", line 19, in <module>
    from prettytensor.pretty_tensor_image_methods import *
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/pretty_tensor_image_methods.py", line 17, in <module>
    from prettytensor import pretty_tensor_class as prettytensor
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/pretty_tensor_class.py", line 1829, in <module>
    tf.ops.register_tensor_conversion_function(
AttributeError: 'module' object has no attribute 'ops'

```

Please let me know any fix for it. Thanks in advance!

**Comment by eiderman** [comment]
I just tried a fresh install of TF and PT and didn't get this error.  Did you also upgrade pretty tensor? There have been a few upstream API changes and these have been incorporated into PT workarounds for this name errors.

**Comment by vignesh10** [comment]
I guess I havent updated prettytensor! I will update and let u know. Thanks!
