### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by apiszcz** [google/prettytensor#43]
__version__ = '0.7.1'

    import prettytensor as pt
  File "lib\prettytensor\__init__.py", line 25, in <module>
    from prettytensor import funcs
  File "lib\prettytensor\funcs.py", line 25, in <module>
    from prettytensor.pretty_tensor_image_methods import *
  File "lib\prettytensor\pretty_tensor_image_methods.py", line 135, in <module>
    class conv2d(prettytensor.VarStoreMethod):
  File "lib\prettytensor\pretty_tensor_image_methods.py", line 145, in conv2d
    bias=tf.zeros_initializer(),
TypeError: zeros_initializer() missing 1 required positional argument: 'shape'

**Comment by eiderman** [comment]
To use tensorflow at head, you need to use pretty tensor at head as well.
The upstream API is rapidly changing.

**Comment by devilwarz** [comment]
Is there any update on this issue? I am facing the exact same issue. 

I am using Python 3.5.2 |Anaconda 4.2.0 (64-bit)| 
```
import tensorflow as tf
import prettytensor as pt
```

Type "help", "copyright", "credits" or "license" for more information.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Continuum\Anaconda3\lib\site-packages\prettytensor-0.7.2-py3.5.egg\pr
ettytensor\__init__.py", line 25, in <module>
    from prettytensor import funcs
  File "C:\Continuum\Anaconda3\lib\site-packages\prettytensor-0.7.2-py3.5.egg\pr
ettytensor\funcs.py", line 25, in <module>
    from prettytensor.pretty_tensor_image_methods import *
  File "C:\Continuum\Anaconda3\lib\site-packages\prettytensor-0.7.2-py3.5.egg\pr
ettytensor\pretty_tensor_image_methods.py", line 135, in <module>
    class conv2d(prettytensor.VarStoreMethod):
  File "C:\Continuum\Anaconda3\lib\site-packages\prettytensor-0.7.2-py3.5.egg\pr
ettytensor\pretty_tensor_image_methods.py", line 145, in conv2d
    bias=tf.zeros_initializer(),
TypeError: zeros_initializer() missing 1 required positional argument: 'shape'

**Comment by eiderman** [comment]
Which version of tensorflow and which version of pretty tensor are you
using? Pip will be updated to be compatible with tensorflow 1.0 soon after
an release candidate, buy ingredients the meantime there are some
incompatibilities and the goal is to have PT at head work with tf head and
nightly builds and pip work with v12 (I.e. pip install tensorflow)

**Comment by devilwarz** [comment]
Hi,
I was able to solve the issue by changing 
`bias=tf.zeros_initializer()`
to 
`bias=none`
I have forked another in https://github.com/devilwarz/prettytensor and introduced the changes and then ran the setup.
@eiderman do you think this is correct?

**Comment by YutingZhang** [comment]
Hi @eiderman, 

Is pretty tensor (pip version, python 3.5) totally compatible with TF1.0?

Thanks!

**Comment by eiderman** [comment]
I just pushed a version that is compatible with TF 1.0.  Sorry for the delay, I was on vacation.

**Comment by YutingZhang** [comment]
@eiderman Thank you so much! It is working.

**Comment by coderguanmingyang** [comment]
`  File "demo/demo.py", line 4, in <module>
    import prettytensor as pt
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/__init__.py", line 25, in <module>
    from prettytensor import funcs
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/funcs.py", line 25, in <module>
    from prettytensor.pretty_tensor_image_methods import *
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/pretty_tensor_image_methods.py", line 135, in <module>
    class conv2d(prettytensor.VarStoreMethod):
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/pretty_tensor_image_methods.py", line 145, in conv2d
    bias=tf.zeros_initializer(),
TypeError: zeros_initializer() takes at least 1 argument (0 given)
`
how can I slove the problem? I think the prettytensor is not fitted the tensorflow, because of the version.

**Comment by coderguanmingyang** [comment]
how can I slove the problem? I think the prettytensor is not fitted the tensorflow, because of the version.


`  File "demo/demo.py", line 4, in <module>
    import prettytensor as pt
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/__init__.py", line 25, in <module>
    from prettytensor import funcs
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/funcs.py", line 25, in <module>
    from prettytensor.pretty_tensor_image_methods import *
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/pretty_tensor_image_methods.py", line 135, in <module>
    class conv2d(prettytensor.VarStoreMethod):
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/pretty_tensor_image_methods.py", line 145, in conv2d
    bias=tf.zeros_initializer(),
TypeError: zeros_initializer() takes at least 1 argument (0 given)

 @eiderman

**Comment by eiderman** [comment]
Which pretty tensor and which tensor flow version?

**Comment by apiszcz** [comment]
Please close this ticket I have moved on to Keras 2 and TF 1.01

**Comment by eiderman** [comment]
I encourage those who open tickets to close them. I'm glad you find a
solution that works for you :-)

**Comment by coderguanmingyang** [comment]
tf version
`>>> import tensorflow
>>> tensorflow.__version__
'1.1.0-rc0'
`
prettytensor version
`>>> import prettytensor
>>> prettytensor.__version__
'0.7.4'
`

yesterday I tried to change the prettytensor to some other versions，such as 0.7.3、0.7.2、0.7.1、 0.6.2，but all failed. 

For example, 0.7.3 the error information is ：
` File "demo/demo.py", line 4, in <module>
    import prettytensor as pt
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/__init__.py", line 25, in <module>
    from prettytensor import funcs
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/funcs.py", line 27, in <module>
    from prettytensor.pretty_tensor_methods import *
  File "/usr/local/lib/python2.7/dist-packages/prettytensor/pretty_tensor_methods.py", line 714, in <module>
    prettytensor.Register(tf.complex_abs)
AttributeError: 'module' object has no attribute 'complex_abs'
`
@eiderman

**Comment by coderguanmingyang** [comment]
#tf version
>>> import tensorflow
>>>tensorflow.version
'1.1.0-rc0'
#prettytensor version
>>> import prettytensor
prettytensor.version
'0.7.4'

yesterday I tried to change the prettytensor to some other versions，such as 0.7.3、0.7.2、0.7.1、 0.6.2，but all failed.

For example, 0.7.3 the error information is ：

File "demo/demo.py", line 4, in <module> import prettytensor as pt
 File "/usr/local/lib/python2.7/dist-packages/prettytensor/__init__.py", line 25, in <module> from prettytensor import funcs 
File "/usr/local/lib/python2.7/dist-packages/prettytensor/funcs.py", line 27, in <module> from prettytensor.pretty_tensor_methods import *
 File "/usr/local/lib/python2.7/dist-packages/prettytensor/pretty_tensor_methods.py", line 714, in <module> prettytensor.Register(tf.complex_abs) 
AttributeError: 'module' object has no attribute 'complex_abs'
@eiderman

**Comment by coderguanmingyang** [comment]
what is the tickets?how to close the tickets? I am confused. thanks for reply~

**Comment by coderguanmingyang** [comment]
what is the tickets?how to close the tickets? I am confused. thanks for reply~ @apiszcz
